language: python

python:
  - 3.7
  - 3.8

install:
  - pip install -e .[deep-learning]
  - pip install -r requirements_test.txt

script:
  - python -m spacy download en_core_web_sm
  - python -m spacy download en_trf_bertbaseuncased_lg
  - pip install git+https://github.com/epfml/sent2vec.git
  - pytest -m  "not (integration or transformers)" --durations=0 --disable-warnings --tb=line --cov=wellcomeml ./tests
  - export WELLCOMEML_ENV=development_transformers && $(VIRTUALENV)/pytest -m "transformers" --durations=0 --disable-warnings --cov-append --tb=line --cov=wellcomeml ./tests/transformers

cache: pip

jobs:
  fast_finish: true
  allow_failures:
     - python: 3.8

branches:
  only:
  - master

after_success:
  - codecov
